OLED_ENABLE = yes
# ENCODER_ENABLE = yes     # Enables the use of one or more encoders, and I don't have any.
RGB_MATRIX_ENABLE = yes     # Disable keyboard RGB matrix, as it is enabled by default on rev3
RGBLIGHT_ENABLE = yes      # Enable keyboard RGB underglow
# KEY_OVERRIDE_ENABLE = yes  # Enables key overrides
REPEAT_KEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
LEADER_ENABLE = yes
COMBO_ENABLE = yes
AUTO_SHIFT_ENABLE = yes
